### ISSUE TITLE
Installer: blank lines and illegible characters in the menu of languages

### ISSUE THREAD

**Issue by grahamperrin** [trueos/pc-sysinstall#4]
TrueOS-Desktop-12.0-CURRENT-2016-08-08-x64-USB.img with an 
HP EliteBook 8540p with UEFI enabled. 

In the menu of languages (apologies for mistakes in my copy typing, some of the non-Roman characters are approximated): 

- a blank line below Afrikaans
- an illegible character in Az\*rbaycanca
- illegible characters in the g\*l\*n below Furlan
- a blank line above Deutsch
- two blank lines above Magyar
- one blank line above and one blank line below Noregian Bokmal 
-  one blank line above Daco
- one blank line above cpnckn
- three blank lines below Svenska
- illegible characters in Ti\*ng Vi\*t

**Comment by grahamperrin** [comment]
@beanpole135 I wonder whether this issue, or an underlying issue, is the root cause (or amongst root causes) of locale-related issues such as https://github.com/trueos/trueos-core/issues/31

**Comment by kmoore134** [comment]
I just fixed this by including the 'noto' fonts again. Turns out noto-lite didn't have all the right fonts we needed. Next ISO will reflect this.
