### ISSUE TITLE
Failed installation finished or aborted, reboot failed

### ISSUE THREAD

**Issue by grahamperrin** [trueos/pc-sysinstall#8]
TrueOS-Desktop--2016-08-10

Following https://github.com/trueos/pc-sysinstall/issues/7 I chose the menu option to reboot. 

Instead of a reboot, the same menu reappeared.

**Comment by grahamperrin** [comment]
Reproducible. 

Boot the installer from a USB flash drive and after the first failed attempt to install, save details to a second USB flash drive then abort, and try to reboot. 

The menu reappears. 

Workaround: a simple press on the power button, to shut down.

**Comment by kmoore134** [comment]
This issue was moved to trueos/trueos-utils-qt5#6
